name: Build Website
env:
  PUBLISH_DIR: website/Samples/
on:
  push:
    branches:  
      - main
      - feature/docs
      
permissions:
  contents: write
  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build-and-publish-website:
    runs-on: windows-latest
    steps:
        
#Begin install mkdocs        
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    - uses: actions/cache@v3
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: pip install mkdocs-material 
    - run: mkdocs gh-deploy --force
#Begin install mkdocs        

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    # .Net 8 update     
    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
         dotnet-version: |
           8.0.x
         include-prerelease: true
    - name: install wasm-tools
      run: dotnet workload install wasm-tools
    - name: Run DocFx
      # Use a .cmd so this script can be run locally for testing
      run: docfx\build-site.cmd
      # build blazor samples to website/samples/
    - name: Build Blazor Website Sample
      shell: pwsh
      run: |
        ./Scripts/BuildSamplesWebsite.ps1     
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
      # Upload the 'website' folder as artifact
        path: 'website'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
