name: Build Docs

on:
  push:
    branches:  
      - feature/build-docs   
  workflow_dispatch:
      
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0      
    - name: Run DocFx
      run: docfx\build-site.cmd      
