name: Build Website

on:
  push:
    branches:  
      - main
      - feature/docs
      
permissions:
  contents: write
  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build-and-publish-website:
    runs-on: windows-latest
    # Environment for GitHub Pages deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
        
#Begin install mkdocs        
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    - uses: actions/cache@v4
      with:
        key: mkdocs-material-${{ env.cache_id }}
        path: .cache
        restore-keys: |
          mkdocs-material-
    - run: |
        pip install mkdocs-material 
        pip install mkdocs-glightbox
#End install mkdocs        

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0         
        filter: tree:0 
    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
         dotnet-version: |
           9.0.203
           8.0.407
    - name: install workloads
      run: dotnet workload install maui macos android ios maccatalyst wasm-tools wasm-tools-net8 
    - name: Run DocFx
      shell: pwsh
      run: ./Scripts/BuildDocumentationWebSite.ps1
      # build blazor samples to website/samples/
    - name: Build Blazor Website Sample
      shell: pwsh
      run: ./Scripts/BuildSamplesWebsite.ps1     
    
    # Configure GitHub Pages
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    # Upload artifact
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./website
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
